-- =========================
-- USERS
-- =========================

INSERT INTO USERS (USER_ID, NAME)
VALUES (1, 'Alice');

INSERT INTO USERS (USER_ID, NAME)
VALUES (2, 'Bob');

INSERT INTO USERS (USER_ID, NAME)
VALUES (3, 'Charlie');


-- =========================
-- PRODUCTS
-- =========================

INSERT INTO PRODUCT (PRODUCT_ID, NAME, BASE_PRICE)
VALUES (101, 'Coke 500ml', 100);

INSERT INTO PRODUCT (PRODUCT_ID, NAME, BASE_PRICE)
VALUES (102, 'Pepsi 500ml', 95);

INSERT INTO PRODUCT (PRODUCT_ID, NAME, BASE_PRICE)
VALUES (103, 'Lays Classic', 50);

INSERT INTO PRODUCT (PRODUCT_ID, NAME, BASE_PRICE)
VALUES (104, 'Dairy Milk', 80);

INSERT INTO PRODUCT (PRODUCT_ID, NAME, BASE_PRICE)
VALUES (105, 'Maggi Noodles', 40);


-- =========================
-- OUTLETS
-- =========================

INSERT INTO OUTLET (OUTLET_ID, NAME, ADDRESS)
VALUES (201, 'Indirapuram Dark Store', 'Indirapuram, Ghaziabad');

INSERT INTO OUTLET (OUTLET_ID, NAME, ADDRESS)
VALUES (202, 'Vaishali Dark Store', 'Vaishali, Ghaziabad');


-- =========================
-- OUTLET INVENTORY
-- =========================

INSERT INTO OUTLET_INVENTORY
    (OUTLET_INVENTORY_ID, OUTLET_ID, PRODUCT_ID, STOCK, SELLING_PRICE)
VALUES (301, 201, 101, 50, 105);

INSERT INTO OUTLET_INVENTORY
    (OUTLET_INVENTORY_ID, OUTLET_ID, PRODUCT_ID, STOCK, SELLING_PRICE)
VALUES (302, 201, 102, 40, 100);

INSERT INTO OUTLET_INVENTORY
    (OUTLET_INVENTORY_ID, OUTLET_ID, PRODUCT_ID, STOCK, SELLING_PRICE)
VALUES (303, 201, 103, 100, 55);

INSERT INTO OUTLET_INVENTORY
    (OUTLET_INVENTORY_ID, OUTLET_ID, PRODUCT_ID, STOCK, SELLING_PRICE)
VALUES (304, 202, 101, 20, 110);

INSERT INTO OUTLET_INVENTORY
    (OUTLET_INVENTORY_ID, OUTLET_ID, PRODUCT_ID, STOCK, SELLING_PRICE)
VALUES (305, 202, 104, 60, 85);

INSERT INTO OUTLET_INVENTORY
    (OUTLET_INVENTORY_ID, OUTLET_ID, PRODUCT_ID, STOCK, SELLING_PRICE)
VALUES (306, 202, 105, 200, 42);


-- =========================
-- CARTS
-- =========================

INSERT INTO CART
    (CART_ID, USER_ID, OUTLET_ID, STATUS)
VALUES (401, 1, 201, 'ACTIVE');

INSERT INTO CART
    (CART_ID, USER_ID, OUTLET_ID, STATUS)
VALUES (402, 2, 202, 'ACTIVE');


-- =========================
-- CART ITEMS
-- =========================

INSERT INTO CART_ITEM
    (CART_ITEM_ID, CART_ID, PRODUCT_ID, QUANTITY)
VALUES (501, 401, 101, 2);

INSERT INTO CART_ITEM
    (CART_ITEM_ID, CART_ID, PRODUCT_ID, QUANTITY)
VALUES (502, 401, 103, 3);

INSERT INTO CART_ITEM
    (CART_ITEM_ID, CART_ID, PRODUCT_ID, QUANTITY)
VALUES (503, 402, 104, 1);

INSERT INTO CART_ITEM
    (CART_ITEM_ID, CART_ID, PRODUCT_ID, QUANTITY)
VALUES (504, 402, 105, 5);


-- =========================
-- ORDERS
-- =========================

INSERT INTO ORDERS
    (ORDER_ID, USER_ID, OUTLET_ID, TOTAL_AMOUNT, CREATED_AT)
VALUES (601, 1, 201, 265, CURRENT_TIMESTAMP);

INSERT INTO ORDERS
    (ORDER_ID, USER_ID, OUTLET_ID, TOTAL_AMOUNT, CREATED_AT)
VALUES (602, 2, 202, 295, CURRENT_TIMESTAMP);


-- =========================
-- ORDER ITEMS
-- =========================

INSERT INTO ORDER_ITEM
    (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, PURCHASED_PRICE)
VALUES (701, 601, 101, 2, 105);

INSERT INTO ORDER_ITEM
    (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, PURCHASED_PRICE)
VALUES (702, 601, 103, 1, 55);

INSERT INTO ORDER_ITEM
    (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, PURCHASED_PRICE)
VALUES (703, 602, 104, 3, 85);

INSERT INTO ORDER_ITEM
    (ORDER_ITEM_ID, ORDER_ID, PRODUCT_ID, QUANTITY, PURCHASED_PRICE)
VALUES (704, 602, 105, 1, 42);